FROM docker.io/crystallang/crystal:latest
WORKDIR /src
COPY --from=podman-cr . /shards/podman-cr
COPY shard.yml .
RUN shards install
COPY . .
RUN shards build --error-trace --release --progress
ENTRYPOINT cp /src/bin/pod /output/pod
