# Probably a good idea to use a two-stage image  to build the release version
FROM docker.io/crystallang/crystal:latest-alpine AS builder
WORKDIR /src
COPY . .
# Get dependencies
RUN shards install
RUN shards build --error-trace --release --progress --static

FROM docker.io/alpine:latest
COPY --from=builder /src/bin/<%= project %> /bin/<%= project %>
# flags and arguments defined in pods.yaml will be appended to this
ENTRYPOINT ["/bin/<%= project %>"]
