FROM <%= image %>
WORKDIR /src
<% if ps = project_specific_setup(false, project) %>
<%= ps %>
<% else %>
COPY . .
ENTRYPOINT ["echo", "this should be a command to build your project for release"]
<% end %>
