FROM docker.io/crystallang/crystal:latest-alpine AS builder
WORKDIR /src
COPY shard.yaml .
# Get dependencies
RUN shards install
# Do the actual compilation and running in the entrypoint allows us to
# mount the source and avoid rebuilding when developing
ENTRYPOINT ["shards", "run", "--error-trace", "--"]
