FROM docker.io/library/ruby:alpine
RUN apk add g++ musl-dev make libstdc++ curl
WORKDIR /src
COPY Gemfile* .
RUN bundle install
EXPOSE 80
ENTRYPOINT ["bundle", "exec", "jekyll", "serve", "--host=0", "--port=80", "-w"]
